name: Build for all platforms

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  Linux_ARM:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build ARM on Bookworm
      run : |
        docker build -t bliss-analyser-cross-bookworm - < docker/Dockerfile_Bookworm
        docker run --rm -v $PWD/target:/build -v $PWD:/src bliss-analyser-cross-bookworm

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: bliss-analyser-linux-arm-bookworm
        path: releases/

# macOs builds are failing: error: could not find system library 'libavutil' required by the 'ffmpeg-sys-next' crate
#  macOS:
#    runs-on: macos-11.0
#
#    steps:
#    - name: Install Rust
#      uses: actions-rs/toolchain@v1
#      with:
#          toolchain: stable
#
#    - name: Checkout
#      uses: actions/checkout@v2
#
#    - name: Install deps
#      run: |
#        brew install ffmpeg@5
#
#    - name: Build
#      run: |
#        mkdir releases
#        cargo build --release
#        strip target/release/bliss-analyser
#        cp target/release/bliss-analyser releases/bliss-analyser
#        cp UserGuide.md releases/README.md
#        cp LICENSE releases/
#        cp configs/macos.ini releases/config.ini
#
#    - name: Upload artifacts
#      uses: actions/upload-artifact@v2
#      with:
#        name: bliss-analyser-mac
#        path: releases/
